name: Publish release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Clean npm install
        run: npm ci
      - name: Install vsce
        run: npm install -g vsce
      - name: Publish
        run: vsce publish -p ${{ secrets.VSCE_PAT }}
      
